package com.myspace.classloading;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label("age")
	private java.lang.Integer age;

	@org.kie.api.definition.type.Label(value = "salary")
	private java.lang.Integer salary;

	public Person() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Integer getSalary() {
		return this.salary;
	}

	public void setSalary(java.lang.Integer salary) {
		this.salary = salary;
	}

	public Person(java.lang.String name, java.lang.Integer age,
			java.lang.Integer salary) {
		this.name = name;
		this.age = age;
		this.salary = salary;
	}

}